### PR TITLE
Update default track quality classifier

### PR DESCRIPTION
**Pull request by cgsavard**
This PR updates the current track quality classifier used in tracking. The update uses new chi2rphi, chi2rz, and bendchi2 bins. This switch can be explained [here](https://indico.cern.ch/event/1058340/contributions/4456095/attachments/2287755/3888672/L1T_7_27_21.pdf).

This PR is correlated to another PR made in the L1 tracking code to update the features of the classifier. You can find this other PR [here](https://github.com/cms-L1TK/cmssw/pull/161).

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by cgsavard** [comment]
Is there anything left to do for this PR to be merged? It looks like it has passed all tests.

**Comment by cecilecaillol** [comment]
+l1

**Comment by smuzaffar** [comment]
@cgsavard , do we need any cms-sw/cmssw PR to go/test with this?

**Comment by cgsavard** [comment]
@smuzaffar The [PR](https://github.com/cms-L1TK/cmssw/pull/161) I linked tested this performance and was already merged so it is ready for the new classifier. The fork of cmssw that these changes went into is getting ready to merge with central cmssw ASAP.

**Comment by smuzaffar** [comment]
+externals

thanks @cgsavard , ok so there is no code in official `cms-sw/cmssw` repo which uses this data file. I see that the data file is only mentioned in https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/L1Trigger/TrackTrigger/python/TrackQualityParams_cfi.py#L4 (https://github.com/cms-sw/cmssw/search?q=GBDT_default ) but `TrackQualityParams` itself is not defined in official cms-sw/cmssw

are there any plans to integrate/test `TrackQualityParams` in official cms-sw/cmssw?

**Comment by cgsavard** [comment]
@smuzaffar The official cms-sw/cmssw repo does use this data file. The data file is in the [TrackQualityParams_cfi.py](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/L1Trigger/TrackTrigger/python/TrackQualityParams_cfi.py#L4) which is then used in the [Tracklet_cfi.py](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/L1Trigger/TrackFindingTracklet/python/Tracklet_cfi.py#L25) and so this file is used whenever the [TTTracksFromTrackletEmulation](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/L1Trigger/TrackFindingTracklet/python/Tracklet_cfi.py#L4) process is used, for example [here](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker_cfg.py#L110). I am just updating the classifier to a newer version which was agreed on by the L1TK group.

**Comment by cgsavard** [comment]
Are there any other questions pertaining to this PR? Can we merge this?

**Comment by perrotta** [comment]
@AdrianoDee, @srimanob FYA

**Comment by srimanob** [comment]
+Upgrade

**Comment by perrotta** [comment]
+1

**Pull request merged**
