### PR TITLE
New Emulated version of track quality BDT

### PR DESCRIPTION
**Pull request by Chriisbrown**
This PR adds the new emulated version of the track quality BDT to cms-data, it will be needed by upcoming changes made to CMSSW from the CMS-L1TK group which adds a full emulation of the track quality BDT. This is the data file for the BDT. There is not yet a PR to CMSSW for the code that uses this BDT

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by tomalin** [comment]
Hi, is there any reason that this has not been merged yet?

**Comment by aloeliger** [comment]
My apologies, this fell off my radar. Is there a corresponding PR to CMSSW for the BDT yet?

**Comment by tomalin** [comment]
@Chriisbrown should comment. The corresponding C++ code change is currently in the development branch of the L1 tracking group, from which we intend making a PR to central CMSSW in the coming week. However, as this PR to cms-data only adds a new file, and doesn't delete any files, it won't break anything if it is merged now.

**Comment by aloeliger** [comment]
> @Chriisbrown should comment. The corresponding C++ code change is currently in the development branch of the L1 tracking group, from which we intend making a PR to central CMSSW in the coming week. However, as this PR to cms-data only adds a new file, and doesn't delete any files, it won't break anything if it is merged now.

@tomalin Is the BDT present in extant workflows? If so I would prefer to test the main PR with this one before committing files, but I guess it really isn't a big problem either way.

**Comment by tomalin** [comment]
> > @Chriisbrown should comment. The corresponding C++ code change is currently in the development branch of the L1 tracking group, from which we intend making a PR to central CMSSW in the coming week. However, as this PR to cms-data only adds a new file, and doesn't delete any files, it won't break anything if it is merged now.
> 
> @tomalin Is the BDT present in extant workflows? If so I would prefer to test the main PR with this one before committing files, but I guess it really isn't a big problem either way.

The L1Track Quality BDT is already in CMSSW_13_2_0, but it uses the file GBDT_default.onnx , which is already in https://github.com/cms-data/L1Trigger-TrackTrigger/tree/main . The new PR that we intend making to CMSSW next week contains an improvement to the L1Track Quality BDT, which will also cause the BDT to read in the new file clf_GBDT_emulation_newKF_digitized.json added by this PR to cms-data, and stop using GBDT_default.onnx . We do not yet delete the latter, although it will no longer be used, to avoid breaking anything during the transition.

**Comment by aloeliger** [comment]
+l1

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
Ok, this only adds a new file, and technically it gives no issues to the current code when merged.
Still, I don't see why we should hurry up and merge it now, when there is not yet any code available able to test it... I can pass over on it. However, what I would change is the name of the file: having "new" in the name can get "old" very soon and become difficult to realize what it contains and when it was actually "new". Could you please rename the file with something more descriptive?

**Comment by tomalin** [comment]
@perrotta This is a chicken & egg situation. When we make the CMSSW PR of for our improved L1 tracking code in the next few days, since this CMSSW PR code will use the data files in https://github.com/cms-data/L1Trigger-TrackTrigger/pull/3 , it will fail CI checks if this cms-data PR has not already been merged.

**Comment by perrotta** [comment]
+1
- This datafile (not yet used or being testable anywhere in the cmssw workflows) has just been renamed since last signauture
- @smuzaffar if you agree this can be merged, assuming all other signatures as already given

**Comment by smuzaffar** [comment]
yes we can merge it ( it just adds a new file)

**Comment by perrotta** [comment]
> @perrotta This is a chicken & egg situation. When we make the CMSSW PR of for our improved L1 tracking code in the next few days, since this CMSSW PR code will use the data files in #3 , it will fail CI checks if this cms-data PR has not already been merged.

Well, in this case the chicken and the egg can even coexist ;-) 
Testing them together, and merging them together once tests succeed is the normal way to proceed in code integration in cmssw. As I wrote, since it doesn't break anything we can even merge this data file before it can be tested, but it was not necessary at all.

**Pull request merged**
